"use strict";
/* Eskolx Authorship — right-margin dots per author chunk.
   Reads .obsidian/eskolx-authorship/cache.json (generated by scripts/authorship.py)
   as a fast path, but ALSO computes git blame client-side so the dots work for
   everyone with zero Python and zero manual refresh — they update on every
   file-open and after each git pull/push.

   One dot per contiguous same-author run; hover reveals author/date/branch/commit
   with a clickable link to the commit (or PR) on GitHub. */

const { Plugin } = require("obsidian");
const { EditorView, gutter, GutterMarker } = require("@codemirror/view");
const { StateField, RangeSet } = require("@codemirror/state");

const MIN_GAP = 6; // merge chunks closer than this (lines) into one dot
const CACHE_PATH = ".obsidian/eskolx-authorship/cache.json";
const MIN_CHUNK = 2; // runs shorter than this merge into the neighboring chunk

// Author-name normalization: GitHub merge commits use the profile display name
// (e.g. "Natnael Getahun") while local commits use git config user.name
// (e.g. "Natnael-Getahun"). Map aliases to one canonical identity so a single
// person never renders as two dot colors.
const AUTHOR_ALIASES = {
	"Natnael Getahun": "Natnael-Getahun",
};

// Deterministic per-author colors (hsl). Pair the color with the name in hover.
const AUTHOR_COLORS = [
	"rgb(255,140,120)",   // salmon
	"rgb(130,180,255)",   // blue
	"rgb(140,220,140)",   // green
	"rgb(240,200,120)",   // amber
	"rgb(200,160,255)",   // lavender
	"rgb(255,170,220)",   // pink
	"rgb(160,230,230)",   // cyan
	"rgb(230,230,150)",   // yellow
	"rgb(190,190,190)",   // grey
];

class DotMarker extends GutterMarker {
	constructor(color, meta) {
		super();
		this.color = color;
		this.meta = meta;
	}
	toDOM(view) {
		const el = document.createElement("div");
		el.className = "eskolx-dot";
		el.style.background = this.color;
		el.setAttribute("data-eskolx-author", this.meta.author);
		el.addEventListener("mouseenter", (ev) => {
			const p = document.createElement("div");
			p.className = "eskolx-dot-popover";
			p.innerHTML = "";
			const a = document.createElement("div");
			a.className = "eskolx-dot-author";
			a.textContent = this.meta.author;
			const m = document.createElement("div");
			m.className = "eskolx-dot-meta";
			m.textContent = this.meta.lines + " line(s) \u00b7 " + this.meta.date +
				(this.meta.branch ? " \u00b7 " + this.meta.branch : "") +
				(this.meta.merged ? " \u00b7 merged" : "");
			p.appendChild(a);
			p.appendChild(m);
			if (this.meta.subject) {
				const s = document.createElement("div");
				s.className = "eskolx-dot-meta";
				s.textContent = this.meta.subject;
				p.appendChild(s);
			}
			// Clickable commit link (and PR link when the commit is a merge).
			if (this.meta.commit && this.meta.repoUrl) {
				const link = document.createElement("a");
				link.className = "eskolx-dot-link";
				link.href = this.meta.repoUrl + "/commit/" + this.meta.commit;
				link.target = "_blank";
				link.rel = "noopener";
				link.textContent = this.meta.commit.slice(0, 7);
				if (this.meta.pr) {
					link.textContent += " \u00b7 PR #" + this.meta.pr;
					link.href = this.meta.repoUrl + "/pull/" + this.meta.pr;
				}
				p.appendChild(link);
			}
			document.body.appendChild(p);
			// Position the popover, clamping it inside the viewport so text
			// never escapes the window.
			const r = el.getBoundingClientRect();
			const pw = p.offsetWidth || 260;
			const ph = p.offsetHeight || 80;
			let left = r.right + 12;
			let top = Math.max(4, r.top);
			if (left + pw > window.innerWidth - 8) left = Math.max(8, r.left - pw - 12);
			if (top + ph > window.innerHeight - 8) top = Math.max(4, window.innerHeight - ph - 8);
			p.style.left = left + "px";
			p.style.top = top + "px";
			el._pop = p;
			// Keep the popover open while the cursor is over it (so the commit/PR
			// link is clickable) — bridge the gap between the dot and the popover
			// so it doesn't vanish while moving toward it.
			const dismiss = () => {
				clearTimeout(el._popTimer);
				if (el._pop) { el._pop.remove(); el._pop = null; }
				document.removeEventListener("scroll", onScroll);
				window.removeEventListener("wheel", onScroll);
			};
			const hideTimer = (ms) => {
				clearTimeout(el._popTimer);
				el._popTimer = setTimeout(dismiss, ms || 700);
			};
			const keepOpen = () => clearTimeout(el._popTimer);
			p.addEventListener("mouseenter", keepOpen);
			p.addEventListener("mouseleave", () => hideTimer(700));
			el.addEventListener("mouseenter", keepOpen);
			el.addEventListener("mouseleave", () => hideTimer(700));
			// Clicking the commit/PR link moves focus to the new tab, so no mouseleave
			// fires — hide it right after the click instead.
			const links = p.querySelectorAll("a");
			links.forEach((l) => l.addEventListener("click", () => hideTimer(150)));
			// Hide when the page scrolls or the mouse wheel turns.
			const onScroll = () => hideTimer(0);
			document.addEventListener("scroll", onScroll, { passive: true });
			window.addEventListener("wheel", onScroll, { passive: true });
			el._hide = () => hideTimer(0);
			el._keep = keepOpen;
		});
		return el;
	}
	eq(other) {
		return other instanceof DotMarker && other.color === this.color;
	}
}

class EskolxAuthorship extends Plugin {
	async onload() {
		this.cache = null;
		this.branch = "main";
		this.mergedCommits = new Set();
		this.repoUrl = "";
		this.blameCache = {}; // path -> { chunks, participants }
		this.loadGitMeta();
		this.registerEditorExtension(this.dotGutter());
		this.registerEvent(this.app.workspace.on("file-open", () => this.loadGitMeta()));
		// Recompute blame for the active file after a pull/push so dots stay fresh.
		this.registerEvent(this.app.workspace.on("file-open", () => this.refreshActiveFile()));
	}

	async loadGitMeta() {
		try {
			const base = this.app.vault.adapter.getBasePath ? this.app.vault.adapter.getBasePath() : ".";
			const branch = await runGit(this, "branch", "--show-current");
			if (branch) this.branch = branch.trim() || "main";
			const log = await runGit(this, "log", "--format=%H", "-50");
			if (log) this.mergedCommits = new Set(log.trim().split("\n"));
			const remote = await runGit(this, "remote", "get-url", "origin");
			if (remote) {
				const u = remote.trim().replace(/\.git$/, "");
				const m = u.match(/github\.com[/:]([^/]+)\/([^/]+)/);
				if (m) this.repoUrl = "https://github.com/" + m[1] + "/" + m[2];
			}
		} catch (e) { /* non-fatal */ }
	}

	async refreshActiveFile() {
		const file = this.app.workspace.getActiveFile();
		if (!file || !file.path.endsWith(".md")) return;
		// Debounce: git blame is cheap but let's not hammer it on every keystroke.
		clearTimeout(this._blameTimer);
		this._blameTimer = setTimeout(() => this.blameFile(file.path), 300);
	}

	async blameFile(path) {
		try {
			const out = await runGit(this, "blame", "--porcelain", "--", path);
			if (!out) return;
			const chunks = parseBlame(out);
			this.blameCache[path] = { chunks, participants: uniqueAuthors(chunks) };
			// Force the editor to re-render the gutter.
			this.app.workspace.getLeavesOfType("markdown").forEach((leaf) => {
				const view = leaf.view;
				if (view && view.editor && view.editor.cm) view.editor.cm.requestMeasure();
			});
		} catch (e) { /* non-fatal */ }
	}

	dotGutter() {
		const field = StateField.define({
			create: () => RangeSet.empty,
			update: (set, tr) => set.map(tr.changes),
		});
		const markers = (view) => {
			const file = view.state.field(require("obsidian").editorInfoField, false);
			const path = file && file.file ? file.file.path : "";
			// Prefer live client-side blame; fall back to the shipped cache.
			let entry = this.blameCache[path];
			if (!entry && this.cache) entry = this.cache.files[path];
			if (!entry || !entry.chunks) return RangeSet.empty;
			const docLines = view.state.doc.lines;
			let fmEnd = 0;
			const lineText = (n) => view.state.doc.line(Math.min(n, docLines)).text.trim();
			if (lineText(1) === "---") {
				for (let i = 2; i <= docLines; i++) {
					if (lineText(i) === "---") { fmEnd = i; break; }
				}
			}
			const range = [];
			let lastEnd = -Infinity;
			let lastAuthor = null;
			let lastMeta = null;
			for (const c of entry.chunks) {
				const sameAuthorGap = (c.start - lastEnd) < MIN_GAP && c.author === lastAuthor;
				if (lastEnd !== -Infinity && sameAuthorGap) {
					lastEnd = c.end;
					if (lastMeta) lastMeta.lines += c.end - c.start + 1;
					continue;
				}
				const color = this.colorFor(c.author);
				const meta = {
					author: c.author,
					date: c.date || "",
					lines: c.end - c.start + 1,
					commit: c.commit || "",
					branch: this.branch,
					merged: this.mergedCommits.has(c.commit || ""),
					subject: c.subject || "",
					repoUrl: this.repoUrl,
					pr: c.pr || "",
				};
				const anchor = Math.min(Math.max(c.start, fmEnd + 1), docLines);
				const from = view.state.doc.line(anchor).from;
				range.push(new DotMarker(color, meta).range(from, from));
				lastEnd = c.end;
				lastAuthor = c.author;
				lastMeta = meta;
			}
			return RangeSet.of(range, true);
		};
		return [
			gutter({ class: "eskolx-dot-gutter", markers, initialSpacer: () => new DotMarker("transparent", {}) }),
			field,
		];
	}

	colorFor(author) {
		if (this.cache && this.cache.authors && this.cache.authors[author]) {
			return this.cache.authors[author].color;
		}
		let h = 0;
		for (let i = 0; i < author.length; i++) h = (h * 31 + author.charCodeAt(i)) >>> 0;
		return AUTHOR_COLORS[h % AUTHOR_COLORS.length];
	}
}

// Parse `git blame --porcelain` output into contiguous same-author chunks.
function parseBlame(out) {
	const lines = [];
	const commitInfo = {};
	let cur = null;
	for (const raw of out.split("\n")) {
		if (raw.startsWith("\t")) {
			lines.push(cur);
			cur = null;
			continue;
		}
		const m = raw.match(/^\^?([0-9a-f]{40}) \d+ \d+/);
		if (m) {
			const commit = m[1];
			if (commitInfo[commit]) {
				cur = commitInfo[commit];
			} else {
				cur = [commit, "", "", "", ""];
				commitInfo[commit] = cur;
			}
			continue;
		}
		if (raw.startsWith("author ")) cur[1] = AUTHOR_ALIASES[raw.slice(7)] || raw.slice(7);
		else if (raw.startsWith("author-time ")) {
			const d = new Date(parseInt(raw.slice(12), 10) * 1000);
			cur[2] = d.toISOString().slice(0, 10) + " " + d.toTimeString().slice(0, 5);
		}
		else if (raw.startsWith("summary ")) cur[3] = raw.slice(8);
		else if (raw.startsWith("previous ")) cur[4] = raw.slice(9).split(" ")[0];
	}
	const chunks = [];
	for (let i = 0; i < lines.length; i++) {
		const [commit, author, date, subject, prev] = lines[i] || ["", "", "", "", ""];
		if (!author || author === "Not Committed Yet") continue;
		if (chunks.length && chunks[chunks.length - 1].author === author &&
			i === chunks[chunks.length - 1].end + 1) {
			chunks[chunks.length - 1].end = i + 1;
			if (!chunks[chunks.length - 1].date && date) chunks[chunks.length - 1].date = date;
			if (!chunks[chunks.length - 1].subject && subject) chunks[chunks.length - 1].subject = subject;
		} else {
			chunks.push({
				start: i + 1, end: i + 1, author, commit, date: date || "",
				subject: subject || "", pr: prFromSubject(subject),
			});
		}
	}
	// Merge runs shorter than MIN_CHUNK into the previous chunk (same author).
	const merged = [];
	for (const c of chunks) {
		if (merged.length && c.author === merged[merged.length - 1].author &&
			(c.end - c.start + 1) < MIN_CHUNK) {
			merged[merged.length - 1].end = c.end;
		} else {
			merged.push(c);
		}
	}
	return merged;
}

function prFromSubject(subject) {
	const m = (subject || "").match(/#(\d+)/);
	return m ? m[1] : "";
}

function uniqueAuthors(chunks) {
	const seen = [];
	for (const c of chunks) if (!seen.includes(c.author)) seen.push(c.author);
	return seen;
}

async function runGit(plugin, ...args) {
	try {
		const base = plugin.app.vault.adapter.getBasePath ? plugin.app.vault.adapter.getBasePath() : ".";
		const proc = await (require("child_process")).execFile(
			"git", ["-C", base, ...args],
			{ timeout: 10000 }
		);
		return new Promise((res, rej) => {
			let out = "";
			proc.stdout.on("data", d => out += d);
			proc.stderr.on("data", () => {});
			proc.on("close", code => code === 0 ? res(out) : rej(new Error("git failed")));
			proc.on("error", rej);
		});
	} catch (e) {
		return null;
	}
}

module.exports = EskolxAuthorship;
