"use strict";
/* Eskolx Authorship — right-margin dots per author chunk.
   Reads .obsidian/eskolx-authorship/cache.json (generated by scripts/authorship.py).
   One dot per contiguous same-author run; hover reveals author/date/branch/commit. */

const { Plugin } = require("obsidian");
const { EditorView, gutter, GutterMarker } = require("@codemirror/view");
const { StateField, RangeSet } = require("@codemirror/state");

const MIN_GAP = 6; // merge chunks closer than this (lines) into one dot
const CACHE_PATH = ".obsidian/eskolx-authorship/cache.json";

class DotMarker extends GutterMarker {
	constructor(color, meta) {
		super();
		this.color = color;
		this.meta = meta;
	}
	toDOM(view) {
		const el = document.createElement("div");
		el.className = "eskolx-dot";
		el.style.background = this.color;
		el.setAttribute("data-eskolx-author", this.meta.author);
		el.addEventListener("mouseenter", (ev) => {
			const p = document.createElement("div");
			p.className = "eskolx-dot-popover";
			p.innerHTML = "";
			const a = document.createElement("div");
			a.className = "eskolx-dot-author";
			a.textContent = this.meta.author;
			const m = document.createElement("div");
			m.className = "eskolx-dot-meta";
			m.textContent = this.meta.lines + " line(s) \u00b7 " + this.meta.date +
				(this.meta.branch ? " \u00b7 " + this.meta.branch : "") +
				(this.meta.merged ? " \u00b7 merged" : "") +
				(this.meta.commit ? " \u00b7 " + this.meta.commit.slice(0, 7) : "");
			if (this.meta.subject) {
				const s = document.createElement("div");
				s.className = "eskolx-dot-meta";
				s.textContent = this.meta.subject;
				p.appendChild(s);
			}
			p.appendChild(a);
			p.appendChild(m);
			document.body.appendChild(p);
			const r = el.getBoundingClientRect();
			p.style.left = (r.right + 12) + "px";
			p.style.top = Math.max(4, r.top) + "px";
			el._pop = p;
		});
		el.addEventListener("mouseleave", () => {
			if (el._pop) { el._pop.remove(); el._pop = null; }
		});
		return el;
	}
	eq(other) {
		return other instanceof DotMarker && other.color === this.color;
	}
}

class EskolxAuthorship extends Plugin {
	async onload() {
		this.cache = null;
		try {
			const raw = await this.app.vault.adapter.read(CACHE_PATH);
			this.cache = JSON.parse(raw);
		} catch (e) {
			console.warn("Eskolx Authorship: no cache yet — run scripts/authorship.py");
		}
		this.branch = "main";
		this.mergedCommits = new Set();
		this.loadGitMeta();
		this.registerEditorExtension(this.dotGutter());
		this.registerEvent(this.app.workspace.on("file-open", () => this.loadGitMeta()));
	}

	async loadGitMeta() {
		try {
			const proc = await this.app.vault.adapter
				.exists(".git") ? await runGit(this, "branch", "--show-current") : null;
			if (proc) this.branch = proc.trim() || "main";
			const log = await runGit(this, "log", "--format=%H", "-50");
			if (log) this.mergedCommits = new Set(log.trim().split("\n"));
		} catch (e) { /* non-fatal */ }
	}

	dotGutter() {
		const field = StateField.define({
			create: () => RangeSet.empty,
			update: (set, tr) => set.map(tr.changes),
		});
		const markers = (view) => {
			if (!this.cache) return RangeSet.empty;
			const file = view.state.field(require("obsidian").editorInfoField, false);
			const path = file && file.file ? file.file.path : "";
			const entry = this.cache.files[path];
			if (!entry || !entry.chunks) return RangeSet.empty;
			// Find the end of the frontmatter block (line N of "--- ... ---")
			// so dots for frontmatter chunks anchor at the first content line.
			const docLines = view.state.doc.lines;
			let fmEnd = 0;
			const lineText = (n) => view.state.doc.line(Math.min(n, docLines)).text.trim();
			if (lineText(1) === "---") {
				for (let i = 2; i <= docLines; i++) {
					if (lineText(i) === "---") { fmEnd = i; break; }
				}
			}
			const range = [];
			let lastEnd = -Infinity;
			let lastAuthor = null;
			let lastMeta = null;
			for (const c of entry.chunks) {
				// Merge only when the SAME author's chunk is close; a new
				// author always gets their own dot, however close.
				const sameAuthorGap = (c.start - lastEnd) < MIN_GAP && c.author === lastAuthor;
				if (lastEnd !== -Infinity && sameAuthorGap) {
					lastEnd = c.end;
					if (lastMeta) lastMeta.lines += c.end - c.start + 1;
					continue;
				}
				const color = this.cache.authors[c.author]?.color || "rgb(190,190,190)";
				const meta = {
					author: c.author,
					date: c.date || "",
					lines: c.end - c.start + 1,
					commit: c.commit || "",
					branch: this.branch,
					merged: this.mergedCommits.has(c.commit || ""),
					subject: c.subject || "",
				};
				// Anchor: chunk start, but never inside the collapsed
				// properties box — frontmatter chunks move to the body start.
				const anchor = Math.min(Math.max(c.start, fmEnd + 1), docLines);
				const from = view.state.doc.line(anchor).from;
				range.push(new DotMarker(color, meta).range(from, from));
				lastEnd = c.end;
				lastAuthor = c.author;
				lastMeta = meta;
			}
			return RangeSet.of(range, true);
		};
		return [
			gutter({ class: "eskolx-dot-gutter", markers, initialSpacer: () => new DotMarker("transparent", {}) }),
			field,
		];
	}
}

async function runGit(plugin, ...args) {
	try {
		const proc = await (require("child_process")).execFile(
			"git", ["-C", plugin.app.vault.adapter.getBasePath ? plugin.app.vault.adapter.getBasePath() : ".", ...args],
			{ timeout: 10000 }
		);
		return new Promise((res, rej) => {
			let out = "";
			proc.stdout.on("data", d => out += d);
			proc.stderr.on("data", () => {});
			proc.on("close", code => code === 0 ? res(out) : rej(new Error("git failed")));
			proc.on("error", rej);
		});
	} catch (e) {
		return null;
	}
}

module.exports = EskolxAuthorship;
